version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: 'cargo'
    directory: '/pydantic-core/'
    schedule:
      interval: 'monthly'
    groups:
      rust-deps:
        patterns:
          - '*'
        # pyo3 updates will require jiter updates, we'll handle them manually anyway
        exclude-patterns:
          - 'pyo3*'
