name: codspeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

env:
  UV_FROZEN: true
  UV_PYTHON: 3.14

jobs:
  codspeed-profiling:
    name: CodSpeed profiling
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      # Using this action is still necessary for CodSpeed to work:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.UV_PYTHON }}

      - name: install deps
        run: uv sync --all-packages --group testing-extra --extra email --frozen

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools

      - name: cache rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: pydantic-core

      - name: install pydantic-core with profiling symbols
        run: |
          cd pydantic-core
          uv pip uninstall pytest-speed
          make build-pgo
        env:
          CARGO_PROFILE_RELEASE_DEBUG: "line-tables-only"
          CARGO_PROFILE_RELEASE_STRIP: "false"

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          run: uv run --no-sync pytest ./tests/benchmarks --codspeed
