name: Dependencies Check

on:
  schedule:
  - cron: '30 19 * * *'
  workflow_dispatch: {}

jobs:
  find_dependency_cases:
    runs-on: ubuntu-latest

    outputs:
      PYTHON_DEPENDENCY_CASES: ${{ steps.list-python-dependencies.outputs.PYTHON_DEPENDENCY_CASES }}

    steps:
    - uses: actions/checkout@v3
    - uses: samuelcolvin/list-python-dependencies@main
      id: list-python-dependencies

  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.PYTHON_DEPENDENCY_CASE }}

    needs:
    - find_dependency_cases

    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.11']
        PYTHON_DEPENDENCY_CASE: ${{ fromJSON(needs.find_dependency_cases.outputs.PYTHON_DEPENDENCY_CASES) }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install -r requirements/testing.txt

    - run: pip install .

    - run: pip install ${{ matrix.PYTHON_DEPENDENCY_CASE }}

    - run: pip freeze

    - run: make test
