name: Docs Preview

on: [pull_request]

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install
      run: make install-docs

    - run: pip install smokeshow

    - name: build site
      run: make docs

    - run: smokeshow upload site
      env:
        SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Docs Preview
        SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
