name: Label & Assign

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

permissions:
  pull-requests: write

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://samuelcolvin/label-and-assign:latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: samuelcolvin,PrettyWood
          awaiting_update_label: 'awaiting author revision'
          awaiting_review_label: 'ready for review'
