name: Pydantic People Update

# on:
#   schedule:
#     - cron: "0 12 1 * *"
#   workflow_dispatch: {}
on: push

jobs:
  pydantic-people:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/people
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
